skills = {
    "alchemist": {
        "description": "Alchemists are learned souls who use hermetic knowledge to create tinctures, balms, acids, transmutations and incendiaries.",
        "beginners_luck": "Will",
        "help": ["Lore Master", "Laborer"],
        "supplies": ["herbs", "roots", "blood", "bones"],
        "gear": "Formulæ",
        "factors": [],
    },
    "arcanist": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "armorer": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "carpenter": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "cartographer": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "commander": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "cook": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "criminal": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "dungeoneer": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "fighter": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "haggler": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "healer": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "hunter": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "laborer": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "lore master": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "manipulator": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "mentor": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "orator": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "pathfinder": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "peasant": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "persuader": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "rider": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "ritualist": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "sailor": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "sapper": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "scavenger": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "scholar": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "scout": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "steward": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "stonemason": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "survivalist": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "theologian": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "weaver": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
}
