skills = {
    "alchemist": {
        "description": "Alchemists are learned souls who use hermetic knowledge to create tinctures, balms, acids, transmutations and incendiaries.",
        "beginners_luck": "Will",
        "help": ["Lore Master", "Laborer"],
        "supplies": ["herbs", "roots", "blood", "bones"],
        "gear": "Formulæ",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
    "name": {
        "description": "",
        "beginners_luck": "",
        "help": [""],
        "supplies": [],
        "gear": "",
        "factors": [],
    },
}
